# Generated by Django 3.1.1 on 2020-11-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_plant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='System',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='system',
            new_name='text',
        ),
    ]
